#if !canImport(ObjectiveC)
import XCTest

extension DisruptorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DisruptorTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(DisruptorTests.__allTests__DisruptorTests),
    ]
}
#endif
