#if !canImport(ObjectiveC)
import XCTest

extension SequencerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SequencerTests = [
        ("testShouldBatchClaim", testShouldBatchClaim),
        ("testShouldClaimSpecificSequence", testShouldClaimSpecificSequence),
        ("testShouldIndicateHasAvailableCapacity", testShouldIndicateHasAvailableCapacity),
        ("testShouldNotBeAvailableUntilPublished", testShouldNotBeAvailableUntilPublished),
        ("testShouldNotifyWaitStrategyOnPublish", testShouldNotifyWaitStrategyOnPublish),
        ("testShouldNotifyWaitStrategyOnPublishBatch", testShouldNotifyWaitStrategyOnPublishBatch),
        ("testShouldStartWithInitialValue", testShouldStartWithInitialValue),
        ("testShouldTryNext", testShouldTryNext),
        ("testShouldWaitOnPublication", testShouldWaitOnPublication),
    ]
}

extension VolatileTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__VolatileTests = [
        ("testVolatileLoadStore", testVolatileLoadStore),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SequencerTests.__allTests__SequencerTests),
        testCase(VolatileTests.__allTests__VolatileTests),
    ]
}
#endif
